### ISSUE TITLE
Provide compatibility with EXT:repeatable_form_elements

### ISSUE THREAD

**Issue by h3nn3s** [pagemachine/typo3-formlog#191]
Hi,

thanks for your extension. 

We use EXT:repeatable_form_elements for different kind of seminar registration for a user definable amount of participants.

Sadly, the formlog extension currently is not capable of handling repeated form elements, which are in the end nested form elements in an array representation.
"repeatable_element.counter.field_identifier" instead of a plain "field_identifier"

**Comment by mbrodala** [comment]
Can you add more details what you see and where? (Log entry records, screenshots, etc.)

**Comment by johfeu** [comment]
I guess he is referring to how those fields are representaed in `\TYPO3\CMS\Form\Domain\Model\FormDefinition::$elementsByIdentifier` (example: ﻿`$formDefinition->elementsByIdentifier["repeatablecontainer-1.0.singleselect-1"]`  )
Not sure how and if that should be fixed in `\Pagemachine\Formlog\Domain\Form\Finishers\LoggerFinisher::getFormValues()` did not look deeper into it. For me the only thing breaking is the json view in the backend module because the Array is treated as a simple value  because it is not catchedy by `hasStringKeys()`. This is causing an Array to string conversion.
For me I justed patched the if clause to check if the first array item is an array as well

```diff
diff --git a/vendor/pagemachine/typo3-formlog/Classes/Rendering/ValueFormatter.php b/vendor/pagemachine/typo3-formlog/Classes/Rendering/ValueFormatter.php
--- a/vendor/pagemachine/typo3-formlog/Classes/Rendering/ValueFormatter.php
+++ b/vendor/pagemachine/typo3-formlog/Classes/Rendering/ValueFormatter.php	(date 1699454148789)
@@ -63,7 +63,7 @@
     {
         $indentation = str_repeat('    ', $level);

-        if ($this->hasStringKeys($value)) {
+        if ($this->hasStringKeys($value) || is_array(reset($value))) {
             $arrayValues = [];

             foreach ($value as $key => $arrayValue) {

```

**Comment by mbrodala** [comment]
@johfeu Can you try the following change?

```diff
--- a/Classes/Rendering/ValueFormatter.php
+++ b/Classes/Rendering/ValueFormatter.php
@@ -89,11 +89,7 @@ final class ValueFormatter
         $arrayValues = [];
 
         foreach ($value as $arrayValue) {
-            $arrayValues[] = sprintf(
-                '%s%s',
-                $indentation,
-                $arrayValue
-            );
+            $arrayValues[] = is_array($arrayValue) ? $this->formatArray($arrayValue, $level) : $this->formatScalar($arrayValue);
         }
 
         return implode("\n", $arrayValues);
```

**Comment by johfeu** [comment]
@mbrodala your approach shows all fields of the repeatable elements flat after each other instead of grouped. I like the nested view better. See screenshots
<img width="478" alt="array" src="https://github.com/pagemachine/typo3-formlog/assets/772962/e4864362-4bab-40fe-a4d8-25130a4afda6">
<img width="499" alt="flat" src="https://github.com/pagemachine/typo3-formlog/assets/772962/e4614101-e4b9-4b57-981c-949d09757360">

**Comment by mbrodala** [comment]
Can anyone provide a real-world formlog entry (DB dump). Redacted data is fine, I just need to be sure to have the proper structure.

**Comment by h3nn3s** [comment]
I am on this project again in this week. I could provide some test data.

**Comment by johfeu** [comment]
I think, this is the one from the screenshot above

```
INSERT INTO `tx_formlog_entries` (`uid`, `pid`, `tstamp`, `crdate`, `deleted`, `language`, `identifier`, `data`, `finisher_variables`)
VALUES
	(71, 26, 1699613454, 1699613454, 0, 0, 'repeatable-test-4', '{\"repeatablecontainer-1\":[{\"text-1\":\"foo1\",\"singleselect-1\":\"firstoption\",\"multiselect-1\":\"\"},{\"text-1\":\"foo2\",\"singleselect-1\":\"secondOption\",\"multiselect-1\":[\"firstoption\",\"secondption\"]}],\"text-2\":\"user input bla\",\"TtJ0s7\":\"\"}', '[]');

```

**Comment by mbrodala** [comment]
Thank you all for your feedback. I've prepared a fix now which basically drops the simplification for plain lists. These are now also rendered with numeric keys but that's fine. Please have a look.

**Comment by h3nn3s** [comment]
Looks good, looking forward to a release

**Comment by mbrodala** [comment]
Thanks for testing, see https://github.com/pagemachine/typo3-formlog/releases/tag/2.2.3
