### ISSUE TITLE
Check conformity to GDPR

### ISSUE THREAD

**Issue by mbrodala** [pagemachine/typo3-formlog#5]
The [GDPR](https://ec.europa.eu/info/law/law-topic/data-protection_en) becomes active with May 25, 2018. We need to check what changes are required to conform to that regulation.

**Comment by Nemo64** [comment]
The person needs to allow the digital processing and storage of their data. Basically, every form needs that now so there is nothing you must do since a required checkbox should do just fine there.

But now speculation: You'll need some kind of proof that the person actually clicked that checkbox. Simply saving that the person did check it might not be enough. I currently also save the ip since that is the only identifying information I have. And since the user allowed me to save his/her personal data, I should be allowed to do so. So If you want to make my live easier, also save the ip of the user. That would have the added benefit of tracing spam attacks easier although the server access log might be enough for that.

**Comment by mbrodala** [comment]
@Nemo64 Thanks for the idea, we'll check if that makes sense.

**Comment by mbrodala** [comment]
This ticket is too broad and specific ones should be created if necessary.
